version: '3.8'

services:
  backend:
    build: ./backend
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/static:/app/static
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge